apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-qwen3-coder-480b-a35b-instruct-fp8
  namespace: liuyunxin
spec:
  storageClassName: gpfs-csi-dynamic
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 488281250Ki
