apiVersion: v1
kind: Secret
metadata:
  name: foldagent-eval-secrets
  namespace: liuyunxin
type: Opaque
stringData:
  judge-openai-api-key: "sk-3bAfYybli7IW4Nmwl7KQiyxFTgnsDs0yJzwbTnMHD5EDTObj"
  openai-api-key: "dummy"
